server:
  port: 8202

spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka,http://user:password@localhost:8762/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 30